language: csharp
solution: sonarcloudtest.sln
mono: none
dotnet: 2.0.5
addons:
  sonarcloud:
    organization: leandowich-github # the key of the org you chose at step #3
    token: $SONAR_TOKEN
    github_token: $GITHUB_TOKEN
    branches:
      - .*

before_install:
  - npm install -g npm
  - bash ./tools/travis-install-dependencies.sh
install:
  - cd sonarcloudtest && npm install && cd ..

script:
  - git fetch --unshallow || true
  - bash ./tools/travis-build.sh