language: csharp
solution: sonarcloudtest.sln
# mono: none
# sudo: required
dotnet: 2.1.4
addons:
  sonarcloud:
    organization: leandowich-github # the key of the org you chose at step #3
    token: $SONAR_TOKEN
    github_token: $GITHUB_TOKEN
    branches:
      - .*

before_install:
  - npm install -g npm

install:
  - cd sonarcloudtest && npm install && cd ..

script:
  - bash ./tools/travis-install-dependencies.sh
  - bash ./tools/travis-build.sh