language: csharp
solution: sonarcloudtest.sln
mono: none
dotnet: 2.1.4
install:
  - dotnet restore
addons:
  sonarcloud:
    organization: leandowich-github # the key of the org you chose at step #3
    token: $SONAR_TOKEN

script:
  - dotnet build
  - sonar-scanner