language: csharp
solution: sonarcloudtest.sln
# mono: none
dotnet: 2.1.4
before_install:
  - npm install -g npm
install:
  - dotnet restore
  - cd sonarcloudtest && npm install && cd ..
addons:
  sonarcloud:
    organization: leandowich-github # the key of the org you chose at step #3
    token: $SONAR_TOKEN
    github_token: $GITHUB_TOKEN
    branches:
      - .*
script:
  - mono ../tools/sonar/SonarQube.Scanner.MSBuild.exe begin /n:NGenerics /k:leandowich-github /d:sonar.login=${SONAR_TOKEN} /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.vstest.reportsPaths="*/TestResults/.trx" /v:"2.0"
  - dotnet build
  - mono ../tools/sonar/SonarQube.Scanner.MSBuild.exe end /d:sonar.login=${SONAR_TOKEN}
#  - sonar-scanner